language: scala
sudo: false
scala:
  - 2.10.6
  - 2.11.7
jdk:
 - openjdk6
 - openjdk7
 - oraclejdk8
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1a7ec8fc9a34c6a9108
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
script: "sbt clean coverage test"
after_success: "sbt coverageAggregate coverageReport coveralls"
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
